### ISSUE TITLE
Looking to Contribute

### ISSUE THREAD

**Issue by LTstrange** [pagekeytech/plaintext-daw#1]
I'm interested in contributing to this project, how can I help?

**Comment by LTstrange** [comment]
I find this project on youtube. It's a very interesting idea！

And I imagined what it may look like in the end. Here are some of my thoughts.

Perhaps it is better to define instruments and songs separately. The definition of instruments should be defined before composition. And songs (or patterns) are created according to the definition of musical instruments.

In this case, users may have a more intuitive experience of some instruments that will be directly provided by plaintext-daw in the future.

**Comment by stephengrice** [comment]
Hey! Thanks, I'm really excited that you want to contribute!
I'm still just working my way through some very basic functionality, trying to make weekly progress. What are your interests? Maybe you can help with design and ideas. As things get larger, maybe you can be in charge of a specific subsystem if you want. Do you have experience with GUIs? That could be very helpful.
Would you be interested in collaborating on a future video? We could do some pair-programming or some kind of podcast discussing features. We have a PageKey Discord, we could chat/screenshare/talk there: https://discord.gg/5m5yFgDPF5
I like the idea of eventually defining instruments and songs separately. It would be cool if instruments could be defined in their own Git repo - to load an instrument, just provide a `git@github.com:whatever/piano.git` url or something like that.

**Comment by stephengrice** [comment]
Closing this out - you're a contributor! Looking forward to working with you more, thanks
